### ISSUE TITLE
Multi-user projects / Collaboration

### ISSUE THREAD

**Issue by sedubois** [graphcool/feature-requests#19]
1. IMHO projects should not be tied to one person but be accessible by different team members.
2. It would be awesome to allow external partners to edit project data by sharing the data browser with them (using the configured permission levels). During prototyping, it is wasteful to add in the front-end editing features which do not target the end-user directly. Such a dashboard could then act as a CMS.

**Comment by matthiasak** [comment]
An additional need here. Allowing team administration abilities here (CMS features mentioned above) it would be awesome to be able to specify a team member's access level, so that they can (in decreasing tiers):

1. SuperAdmin - create/edit schema, configure user access levels, as well as below
2. Admin - create/edit rows in certain tables, as well as below
3. User - read rows in certain tables

Not sure what other variations should exist, but this would be major :100:

**Comment by sedubois** [comment]
I see in your roadmap that this is WIP, looking forward to it 😃

**Comment by sorenbs** [comment]
@sedubois In the first version we will allow you to invite collaborators to a project, but they will all have admin level access. Is this gonna be an issue for you?

**Comment by sedubois** [comment]
In the beginning it's not an issue 👍 but would need to be fixed for sure because it just increases so much the potential accidents of all stakeholders can change everything...

**Comment by marktani** [comment]
This is now available :tada: Finer access control will be possible soon, see #94.
