### ISSUE TITLE
Make Relation Fields Required

### ISSUE THREAD

**Issue by thomaswright** [graphcool/feature-requests#41]
Add a toggle to make relation fields required, just like you can with scalar fields, when creating a node.

**Comment by schickling** [comment]
Very good point. This is fairly important!

**Comment by sedubois** [comment]
Any news on this front?

**Comment by schickling** [comment]
Hi @sedubois! This feature is now in beta.

Feel free to ping us in Slack to get access to this new feature.

**Comment by marktani** [comment]
This is now available to everyone. Note that *to-many* relational fields are always required. If a node is not connected to any nodes in such a relation, it is the empty list `[]`.

You can set a relation to required both in the UI and the schema file.
If you need more information, please consult [the forum](https://graph.cool/forum).

**Comment by sedubois** [comment]
Thanks great news! 

I tried to use this, but I don't see a way to make a relation required through the UI.

I also couldn't make it required through the schema, getting `Errors: course: The relation field `course` cannot be made required, because there are already instances of the enclosing type that violate this constraint.`

However, I only have three instances which all three have a proper value for this field.

I think documentation would be helpful for this. Any pointers?

**Comment by marktani** [comment]
This looks to be an issue with migrating an existing optional relation to a required relation. Here's a bug tracker: https://github.com/graphcool/api-bugs/issues/90.

You need to hover the relation field to enable the selection between required/optional:

![image](https://cloud.githubusercontent.com/assets/1780597/26833581/27b73184-4ad3-11e7-9355-24759aa5f14f.png)

**Comment by sedubois** [comment]
Thanks @marktani. I don't see this required/optional toggle, maybe related to the bug you linked?

Regardless of where I hover with my mouse on this wizard, I don't see this toggle appearing.

<img width="680" alt="screen shot 2017-06-06 at 16 22 52" src="https://cloud.githubusercontent.com/assets/4217871/26834057/7f005384-4ad4-11e7-950e-e88f5858ad23.png">

**Comment by marktani** [comment]
No, this is a separate bug - could you please create [a new issue here](https://github.com/graphcool/console/issues/new)?
