### ISSUE TITLE
Provisioning API: Model/Relations/Project changes via API

### ISSUE THREAD

**Issue by paulosuzart** [graphcool/feature-requests#51]
Hi,

that would be super handy to have a full admin API where we could do most of the things, if not all, provided by the admin console. For our point of view the most priority would be:

   1. Create/Modify Models
   2. Create/Modify Relations
   3. Create/Modify Projects
   4. Create/Modify Permissions

So we can quickly create projects and scale fast for many customers/projects without having to manually do things in the admin console.

**Comment by schickling** [comment]
Hey @paulosuzart. That's already possible based on our internal "System API" but is yet undocumented since we're changing (and breaking) this API quite frequently. We're having plans though to make this API openly available in the future.

We're also working on easier ways to import/export schemas without the UI console.

**Comment by marktani** [comment]
> We're also working on easier ways to import/export schemas without the UI console.

another interesting feature in that direction would be to edit a current schema file using a text editor. so rather an update than a full import of a schema file

**Comment by marktani** [comment]
Closing in favor of #96
