### ISSUE TITLE
Synchronous Mutation Callback

### ISSUE THREAD

**Issue by sorenbs** [graphcool/feature-requests#58]
It should be possible to specify that a Mutation Callback is synchronous.

The semantics should be:

1. a mutation is executed
2. all synchronous webhooks are executed. They have a timeout of 5 seconds.
3.
  *  if at least one synchronous webhook fails or times out we immediately return and include an error message in the response. No async webhooks are executed, but the data in the graphcool project has already been updated
  * if all synchronous webhooks succeed we return a successful response and perform all async webhooks.

**Comment by ejoebstl** [comment]
I one-up this. 

At the current state, it is hard to build robust business logic upon graphcool, since we have no way to propagate errors. 
Given how graphcool works, Projects potentially consist of multiple microservices that are interconnected, so halfway-completed updates might bring the application to an inconsistent state. 

I would also propose an option to update the data only if the synchronous callback succeeded.

**Comment by marktani** [comment]
Functions along [the request pipeline](https://www.graph.cool/docs/reference/functions/request-pipeline/overview-pa6guruhaf/) are synchronous and `TRANSFORM_ARGUMENT` and `PRE_WRITE` fulfill the characteristics described in this feature request.
