### ISSUE TITLE
Arbitrary-precision field type

### ISSUE THREAD

**Issue by marktani** [graphcool/feature-requests#85]
A more suitable type for highly precision-relying use cases like money/physics.

This looks promising: https://github.com/non/spire

**Comment by marktani** [comment]
As additional information, our `Float` type is implemented using Scala's `BigDecimal`. More information can be found here: https://www.graph.cool/docs/reference/platform/fields-teizeit5se#float

It's not arbitrary precision, but provides precision up to 30 digits after the decimal point.

**Comment by pso-aeb** [comment]
BigDecimal is definitively precise enough to handle decimal values "in-code".
My concern is loss of precision when storing values in the database.

FLOAT/DOUBLE can have loss of precision (see https://dev.mysql.com/doc/refman/5.7/en/floating-point-types.html). For many use cases the precision loss is so minor that it can be ignored. For these use cases you should use FLOAT/DOUBLE since they use less space and can be handled fast.

DECIMAL/NUMERIC is recommended to preserve exact precision (see https://dev.mysql.com/doc/refman/5.7/en/fixed-point-types.html).

**Comment by marktani** [comment]
In this case, I'm closing the issue.

We are already using the `DECIMAL(65, 30)` column type for float fields. This provides a high precision with minimal information loss when storing data.

**Comment by lucfranken** [comment]
Currently we store money values in cents in an integer. That's just based on intuition. Does it make sense to use the float fields for it? It feels strange that a float is implemented as a Decimal. 

So it might be a good solution but then the name float sounds off. Floating points in my mind says: "Precision issues when dividing". But maybe the Graph Cool implementation is better than a float?

**Comment by ryall** [comment]
I agree with @lucfranken  - the type should be called Decimal not Float - it is currently misleading.
